const STORAGE_KEY = 'badaMarketProducts';
const RESERVATION_KEY = 'badaMarketReservations';
const USER_KEY = 'badaMarketCurrentUser';

const initialProducts = [
  { id: 'seed-1', boat: '새벽바다호', name: '활 꽃게', type: '일반', price: 18000, quantity: 35, reserved: 8, arrival: '2026-07-28T15:30', status: '입항 예정' },
  { id: 'seed-2', boat: '푸른파도호', name: '못난이 광어', type: '못난이', price: 12000, quantity: 20, reserved: 5, arrival: '2026-07-28T16:10', status: '입항 예정' }
];

function getProducts() { const saved = localStorage.getItem(STORAGE_KEY); if (!saved) { localStorage.setItem(STORAGE_KEY, JSON.stringify(initialProducts)); return initialProducts; } return JSON.parse(saved); }
function saveProducts(items) { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); }
function getReservations() { return JSON.parse(localStorage.getItem(RESERVATION_KEY) || '[]'); }
function won(n) { return n.toLocaleString('ko-KR') + '원'; }
function remaining(p) { return p.quantity - p.reserved; }
function dateText(value) { const d = new Date(value); return `${d.getMonth()+1}월 ${d.getDate()}일 ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`; }
function escapeHtml(v) { return String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function reservationProduct(reservation) { return getProducts().find(p => p.id === reservation.productId) || getProducts().find(p => p.name === reservation.name && p.boat === reservation.boat); }
function reservationArrival(reservation) { return reservation.arrival || reservationProduct(reservation)?.arrival; }
function cancellable(reservation) { const arrival=reservationArrival(reservation); return arrival && Date.now() < new Date(arrival).getTime() - 60 * 60 * 1000; }

function currentUser() { return localStorage.getItem(USER_KEY) || ''; }
function login(e) { e.preventDefault(); const name = document.getElementById('nickname').value.trim(); if (!name) return; localStorage.setItem(USER_KEY, name); updateUserName(); showToast(`${name}님, 환영합니다.`); }
function logout() { localStorage.removeItem(USER_KEY); document.getElementById('nickname').value = ''; goHome(); showToast('로그아웃되었습니다.'); }
function updateUserName() { document.querySelectorAll('.user-name').forEach(el => el.textContent = currentUser()); }
function startAs(role) { if (!currentUser()) { document.getElementById('nickname').focus(); return showToast('닉네임을 입력해 로그인해주세요.'); } document.getElementById('roleScreen').classList.add('hidden'); document.getElementById(role + 'Screen').classList.remove('hidden'); updateUserName(); renderAll(); }
function goHome() { document.querySelectorAll('.screen').forEach(s => s.classList.add('hidden')); document.getElementById('roleScreen').classList.remove('hidden'); }
function toggleProductForm() { const form=document.getElementById('productForm'); form.classList.toggle('hidden'); if (!form.classList.contains('hidden') && !form.dataset.editing) { form.reset(); document.getElementById('productSubmit').textContent='판매 정보 등록하기'; } }
function showToast(message) { const el = document.getElementById('toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2200); }

function productCard(p, fisher = false) {
  const left = remaining(p), percent = p.quantity ? (p.reserved / p.quantity) * 100 : 0;
  const fisherActions = p.owner === currentUser() ? `<select class="select-status" onchange="updateStatus('${p.id}', this.value)"><option ${p.status === '입항 예정' ? 'selected':''}>입항 예정</option><option ${p.status === '입항 중' ? 'selected':''}>입항 중</option><option ${p.status === '입항 완료' ? 'selected':''}>입항 완료</option></select><button class="edit" onclick="editProduct('${p.id}')">수정</button>` : '<span>내 등록 상품만 수정 가능</span>';
  return `<article class="product"><div class="product-head"><span class="fish-icon">${p.type === '못난이' ? '🐟' : '🦐'}</span><div><h4>${escapeHtml(p.name)} ${p.type === '못난이' ? '<small style="color:#e26b2f">못난이</small>' : ''}</h4><p class="boat">${escapeHtml(p.boat)} · ${dateText(p.arrival)}</p></div><span class="status ${p.status === '입항 완료' ? 'arrived' : ''}">${p.status}</span></div><div class="meta"><span>가격 <strong>${won(p.price)}</strong></span><span>남은 수량 <strong>${left}개</strong></span></div><div class="progress"><i style="width:${percent}%"></i></div><div class="product-footer"><span>예약 ${p.reserved}개 / 전체 ${p.quantity}개</span>${fisher ? fisherActions : (left > 0 && p.status !== '입항 완료' ? `<div class="reserve-row"><input id="qty-${p.id}" type="number" min="1" max="${left}" value="1" aria-label="예약 수량" /><button class="primary small" onclick="reserveProduct('${p.id}')">예약하기</button></div>` : '<b>예약 마감</b>')}</div></article>`;
}
function renderFisher() { const items = getProducts(); const reserved = items.reduce((a,p)=>a+p.reserved,0), stock=items.reduce((a,p)=>a+remaining(p),0), sales=items.reduce((a,p)=>a+p.reserved*p.price,0); document.getElementById('fisherSummary').innerHTML = `<div class="summary"><span>예약 수량</span><strong>${reserved}개</strong></div><div class="summary"><span>남은 재고</span><strong>${stock}개</strong></div><div class="summary"><span>예상 매출</span><strong>${won(sales)}</strong></div>`; document.getElementById('fisherProducts').innerHTML = items.length ? items.map(p=>productCard(p,true)).join('') : '<p class="empty">등록된 수산물이 없습니다.</p>'; }
function renderCitizen() { const items=getProducts(); document.getElementById('productCount').textContent=`${items.length}건`; document.getElementById('citizenProducts').innerHTML=items.length ? items.map(p=>productCard(p)).join('') : '<p class="empty">입항 예정 수산물이 없습니다.</p>'; const rs=getReservations().filter(r => r.user === currentUser()); document.getElementById('reservationList').innerHTML=rs.length ? rs.map(r=>{ const canCancel=cancellable(r), arrival=reservationArrival(r); return `<div class="reservation"><div><strong>${escapeHtml(r.name)} <small>${escapeHtml(r.boat)} · ${r.quantity}개 · 입항 ${arrival ? dateText(arrival) : '시간 정보 없음'}</small></strong></div><div class="reservation-actions"><b>${won(r.total)}</b><button class="cancel" ${canCancel ? '' : 'disabled'} title="입항 예정 1시간 전까지 취소할 수 있습니다" onclick="cancelReservation('${r.id}')">${canCancel ? '예약 취소' : '취소 마감'}</button></div></div>`; }).join('') : '<p class="empty">아직 예약한 수산물이 없습니다.</p>'; }
function renderAll() { renderFisher(); renderCitizen(); }
function addProduct(e) { e.preventDefault(); const editingId=e.target.dataset.editing; const products=getProducts(); if (editingId) { const item=products.find(p=>p.id===editingId && p.owner===currentUser()); if (!item) return showToast('내가 등록한 상품만 수정할 수 있습니다.'); const newQuantity=Number(productQuantity.value); if (newQuantity < item.reserved) return showToast(`예약 수량 ${item.reserved}개보다 적게 설정할 수 없습니다.`); Object.assign(item,{boat:boatName.value.trim(),name:productName.value.trim(),type:productType.value,price:Number(productPrice.value),quantity:newQuantity,arrival:arrivalTime.value}); delete e.target.dataset.editing; document.getElementById('productSubmit').textContent='판매 정보 등록하기'; saveProducts(products); showToast('상품 정보를 수정했습니다.'); } else { products.unshift({id:Date.now().toString(),owner:currentUser(),boat:boatName.value.trim(),name:productName.value.trim(),type:productType.value,price:Number(productPrice.value),quantity:Number(productQuantity.value),reserved:0,arrival:arrivalTime.value,status:'입항 예정'}); saveProducts(products); showToast('수산물 판매 정보가 등록되었습니다.'); } e.target.reset(); e.target.classList.add('hidden'); renderAll(); }
function editProduct(id) { const item=getProducts().find(p=>p.id===id && p.owner===currentUser()); if (!item) return showToast('내가 등록한 상품만 수정할 수 있습니다.'); const form=document.getElementById('productForm'); boatName.value=item.boat; productName.value=item.name; productType.value=item.type; productPrice.value=item.price; productQuantity.value=item.quantity; arrivalTime.value=item.arrival; form.dataset.editing=id; document.getElementById('productSubmit').textContent='상품 정보 저장하기'; form.classList.remove('hidden'); form.scrollIntoView({behavior:'smooth',block:'center'}); }
function updateStatus(id, status) { const items=getProducts(); const product=items.find(p=>p.id===id && p.owner===currentUser()); if (!product) return showToast('내가 등록한 상품만 변경할 수 있습니다.'); product.status=status; saveProducts(items); renderAll(); showToast('입항 상태를 변경했습니다.'); }
function reserveProduct(id) { if (!currentUser()) return showToast('로그인 후 예약할 수 있습니다.'); const qty=Number(document.getElementById('qty-'+id).value); const items=getProducts(), p=items.find(x=>x.id===id); if (!Number.isInteger(qty)||qty<1||qty>remaining(p)) return showToast('남은 수량 안에서 선택해주세요.'); p.reserved+=qty; saveProducts(items); const reservations=getReservations(); reservations.unshift({id:Date.now().toString(),productId:p.id,user:currentUser(),name:p.name,boat:p.boat,quantity:qty,total:qty*p.price,arrival:p.arrival,status:p.status}); localStorage.setItem(RESERVATION_KEY,JSON.stringify(reservations)); renderAll(); showToast(`${p.name} ${qty}개를 예약했습니다.`); }
function cancelReservation(reservationId) { const reservations=getReservations(); const reservation=reservations.find(r => String(r.id) === String(reservationId) && r.user === currentUser()); if (!reservation) return showToast('내 예약을 찾을 수 없습니다.'); if (!cancellable(reservation)) return showToast('입항 예정 1시간 전부터는 예약을 취소할 수 없습니다.'); const products=getProducts(); const product=products.find(p => p.id === reservation.productId) || products.find(p => p.name === reservation.name && p.boat === reservation.boat); if (!product) return showToast('수산물 정보를 찾을 수 없어 취소할 수 없습니다.'); product.reserved=Math.max(0, product.reserved-reservation.quantity); saveProducts(products); localStorage.setItem(RESERVATION_KEY, JSON.stringify(reservations.filter(r => String(r.id) !== String(reservationId)))); renderAll(); showToast('예약이 취소되어 재고에 반영되었습니다.'); }
document.addEventListener('DOMContentLoaded', () => { getProducts(); const now=new Date(); now.setHours(now.getHours()+3); document.getElementById('arrivalTime').value=now.toISOString().slice(0,16); const user=currentUser(); if(user) document.getElementById('nickname').value=user; updateUserName(); });
